# Generated by Django 2.2.7 on 2019-12-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
                ('b_name', models.CharField(max_length=100)),
                ('b_contact', models.CharField(max_length=12)),
                ('b_debit', models.IntegerField(verbose_name=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
